{
  "openapi": "3.0.0",
  "info": {
    "title": "Talent Match Backend API",
    "version": "1.0.0",
    "description": ""
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Local development server"
    },
    {
      "url": "https://talent-match-backend.onrender.com",
      "description": "Production server"
    }
  ],
  "paths": {
    "/api/user/user_info": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "取得使用者資訊",
        "description": "",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserInfoResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/UserInfoResponseModel"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/api/auth/login": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "使用者登入",
        "description": "",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponseModel"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              }
            }
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequestModel"
              }
            }
          }
        }
      }
    },
    "/api/auth/register": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "使用者註冊",
        "description": "",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegisterResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/RegisterResponseModel"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              }
            }
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegisterRequestModel"
              }
            }
          }
        }
      }
    },
    "/api/auth/refresh": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "取得新的 Access Token",
        "description": "",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RefreshResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/RefreshResponseModel"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              }
            }
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RefreshRequestModel"
              }
            }
          }
        }
      }
    },
    "/api/auth/google": {
      "get": {
        "tags": [
          "Auth"
        ],
        "summary": "Google登入",
        "description": "",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GoogleResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/GoogleResponseModel"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              }
            }
          }
        }
      }
    },
    "/api/auth/google/callback": {
      "get": {
        "tags": [
          "Auth"
        ],
        "summary": "Google登入Callback",
        "description": "",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GoogleClientResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/GoogleClientResponseModel"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              }
            }
          }
        }
      }
    },
    "/api/auth/reset_password/send_email": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "重設密碼",
        "description": "",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResetPasswordSendEmailResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/ResetPasswordSendEmailResponseModel"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              }
            }
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ResetPasswordSendEmailRequestModel"
              }
            }
          }
        }
      }
    },
    "/api/auth/reset_password/update": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "更新密碼",
        "description": "",
        "parameters": [
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResetPasswordUpdateResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/ResetPasswordUpdateResponseModel"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              }
            }
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ResetPasswordUpdateRequestModel"
              }
            }
          }
        }
      }
    },
    "/api/student_info/basic_info": {
      "get": {
        "tags": [
          "Student_Info"
        ],
        "summary": "取得學生基本資訊",
        "description": "",
        "responses": {
          "default": {
            "description": ""
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "patch": {
        "tags": [
          "Student_Info"
        ],
        "summary": "更新學生基本資訊",
        "description": "",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "boolean",
                      "example": true
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "更新學生基本資訊成功"
                        }
                      }
                    }
                  },
                  "xml": {
                    "name": "main"
                  }
                }
              },
              "application/xml": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "boolean",
                      "example": true
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "更新學生基本資訊成功"
                        }
                      }
                    }
                  },
                  "xml": {
                    "name": "main"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "boolean",
                      "example": false
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "更新學生基本資訊失敗"
                        }
                      }
                    }
                  },
                  "xml": {
                    "name": "main"
                  }
                }
              },
              "application/xml": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "boolean",
                      "example": false
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "更新學生基本資訊失敗"
                        }
                      }
                    }
                  },
                  "xml": {
                    "name": "main"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "boolean",
                      "example": false
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "伺服器錯誤"
                        }
                      }
                    }
                  },
                  "xml": {
                    "name": "main"
                  }
                }
              },
              "application/xml": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "boolean",
                      "example": false
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "伺服器錯誤"
                        }
                      }
                    }
                  },
                  "xml": {
                    "name": "main"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/api/student_info/teacher_apply": {
      "post": {
        "tags": [
          "TeacherInfo"
        ],
        "summary": "申請老師",
        "description": "",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PostTeacherInfoResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/PostTeacherInfoResponseModel"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PostTeacherInfoRequestModel"
              }
            }
          }
        }
      }
    },
    "/api/upload/file": {
      "post": {
        "tags": [
          "Upload"
        ],
        "summary": "上傳檔案",
        "description": "上傳檔案",
        "parameters": [
          {
            "name": "path",
            "in": "formData",
            "description": "上傳檔案的路徑",
            "required": true,
            "enum": [
              "user",
              "course"
            ],
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "file",
            "in": "formData",
            "description": "檔案",
            "required": true,
            "schema": {
              "type": "file"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "上傳成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "properties": {
                      "type": "object",
                      "properties": {
                        "fileUrl": {
                          "type": "object",
                          "properties": {
                            "type": {
                              "type": "string",
                              "example": "string"
                            },
                            "description": {
                              "type": "string",
                              "example": "檔案的網址"
                            }
                          }
                        }
                      }
                    }
                  },
                  "xml": {
                    "name": "main"
                  }
                }
              },
              "application/xml": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "properties": {
                      "type": "object",
                      "properties": {
                        "fileUrl": {
                          "type": "object",
                          "properties": {
                            "type": {
                              "type": "string",
                              "example": "string"
                            },
                            "description": {
                              "type": "string",
                              "example": "檔案的網址"
                            }
                          }
                        }
                      }
                    }
                  },
                  "xml": {
                    "name": "main"
                  }
                }
              }
            }
          },
          "400": {
            "description": "尚未上傳檔案"
          },
          "500": {
            "description": "上傳失敗"
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "path": {
                    "type": "string",
                    "enum": [
                      "user",
                      "course"
                    ]
                  },
                  "file": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/shop/cart": {
      "get": {
        "tags": [
          "Shop"
        ],
        "summary": "取得購物車項目列表",
        "description": "",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetCartItemsResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/GetCartItemsResponseModel"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "post": {
        "tags": [
          "Shop"
        ],
        "summary": "新增購物車項目",
        "description": "",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddCartItemResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/AddCartItemResponseModel"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddCartItemRequestModel"
              }
            }
          }
        }
      }
    },
    "/api/shop/cart/{id}": {
      "delete": {
        "tags": [
          "Shop"
        ],
        "summary": "刪除購物車項目",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RemoveCartItemResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/RemoveCartItemResponseModel"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error400ResponseModel"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error500ResponseModel"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    },
    "schemas": {
      "StringValueModel": {
        "type": "string",
        "example": "string"
      },
      "Error400ResponseModel": {
        "type": "object",
        "required": [
          "status",
          "message"
        ],
        "properties": {
          "status": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          }
        },
        "example": {
          "status": "false",
          "message": "錯誤訊息"
        }
      },
      "Error500ResponseModel": {
        "type": "object",
        "required": [
          "status",
          "message"
        ],
        "properties": {
          "status": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          }
        },
        "example": {
          "status": "false",
          "message": "伺服器錯誤"
        }
      },
      "LoginRequestModel": {
        "type": "object",
        "required": [
          "email",
          "password"
        ],
        "properties": {
          "email": {
            "type": "string",
            "description": "用戶的電子郵件地址"
          },
          "password": {
            "type": "string",
            "description": "用戶的密碼"
          }
        },
        "example": {
          "email": "user@example.com",
          "password": "yourpassword"
        }
      },
      "LoginResponseModel": {
        "type": "object",
        "required": [
          "status",
          "data"
        ],
        "properties": {
          "status": {
            "type": "boolean"
          },
          "data": {
            "type": "object",
            "required": [
              "access_token",
              "refresh_token"
            ],
            "properties": {
              "access_token": {
                "type": "string",
                "description": "登入驗證token"
              },
              "refresh_token": {
                "type": "string",
                "description": "刷新驗證token"
              }
            }
          }
        },
        "example": {
          "status": true,
          "data": {
            "access_token": "string",
            "refresh_token": "string"
          }
        }
      },
      "RegisterRequestModel": {
        "type": "object",
        "required": [
          "nick_name",
          "email",
          "password",
          "confirm_password"
        ],
        "properties": {
          "nick_name": {
            "type": "string",
            "description": "用戶的暱稱"
          },
          "email": {
            "type": "string",
            "description": "用戶的電子郵件地址"
          },
          "password": {
            "type": "string",
            "description": "用戶的密碼"
          },
          "confirm_password": {
            "type": "string",
            "description": "確認用戶的密碼"
          }
        },
        "example": {
          "nick_name": "string",
          "email": "string",
          "password": "string",
          "confirm_password": "string"
        }
      },
      "RegisterResponseModel": {
        "type": "object",
        "required": [
          "status",
          "data"
        ],
        "properties": {
          "status": {
            "type": "boolean"
          },
          "data": {
            "type": "object",
            "required": [
              "message"
            ],
            "properties": {
              "message": {
                "type": "string"
              }
            }
          }
        },
        "example": {
          "status": true,
          "data": {
            "message": "註冊成功"
          }
        }
      },
      "RefreshRequestModel": {
        "type": "object",
        "required": [
          "refresh_token"
        ],
        "properties": {
          "refresh_token": {
            "type": "string",
            "description": "刷新驗證token"
          }
        },
        "example": {
          "refresh_token": "string"
        }
      },
      "RefreshResponseModel": {
        "type": "object",
        "required": [
          "status",
          "data"
        ],
        "properties": {
          "status": {
            "type": "boolean"
          },
          "data": {
            "type": "object",
            "required": [
              "access_token",
              "refresh_token"
            ],
            "properties": {
              "access_token": {
                "type": "string",
                "description": "登入驗證token"
              },
              "refresh_token": {
                "type": "string",
                "description": "刷新驗證token"
              }
            }
          }
        },
        "example": {
          "status": true,
          "data": {
            "access_token": "string",
            "refresh_token": "string"
          }
        }
      },
      "GoogleResponseModel": {
        "type": "object",
        "required": [
          "status",
          "data"
        ],
        "properties": {
          "status": {
            "type": "boolean"
          },
          "data": {
            "type": "object",
            "required": [
              "message"
            ],
            "properties": {
              "message": {
                "type": "string"
              }
            }
          }
        },
        "example": {
          "status": true,
          "data": {
            "message": "已啟動OAuth登入流程"
          }
        }
      },
      "GoogleClientRequestModel": {
        "type": "object",
        "required": [
          "grant"
        ],
        "properties": {
          "grant": {
            "type": "string",
            "description": "OAuth授權碼"
          }
        },
        "example": {
          "grant": "string"
        }
      },
      "GoogleClientResponseModel": {
        "type": "object",
        "required": [
          "status",
          "data"
        ],
        "properties": {
          "status": {
            "type": "boolean"
          },
          "data": {
            "type": "object",
            "required": [
              "access_token",
              "refresh_token"
            ],
            "properties": {
              "access_token": {
                "type": "string",
                "description": "登入驗證token"
              },
              "refresh_token": {
                "type": "string",
                "description": "刷新驗證token"
              }
            }
          }
        },
        "example": {
          "status": true,
          "data": {
            "access_token": "string",
            "refresh_token": "string"
          }
        }
      },
      "ResetPasswordSendEmailRequestModel": {
        "type": "object",
        "required": [
          "email"
        ],
        "properties": {
          "email": {
            "type": "string",
            "description": "用戶的電子郵件地址"
          }
        },
        "example": {
          "email": ""
        }
      },
      "ResetPasswordSendEmailResponseModel": {
        "type": "object",
        "required": [
          "status",
          "data"
        ],
        "properties": {
          "status": {
            "type": "boolean"
          },
          "data": {
            "type": "object",
            "required": [
              "message"
            ],
            "properties": {
              "message": {
                "type": "string"
              }
            }
          }
        },
        "example": {
          "status": true,
          "data": {
            "message": "已寄送重設密碼信"
          }
        }
      },
      "ResetPasswordUpdateRequestModel": {
        "type": "object",
        "required": [
          "password",
          "confirm_password"
        ],
        "properties": {
          "token": {
            "type": "string",
            "description": "重設密碼token"
          },
          "password": {
            "type": "string",
            "description": "用戶的密碼"
          },
          "confirm_password": {
            "type": "string",
            "description": "確認用戶的密碼"
          }
        },
        "example": {
          "token": "string",
          "password": "string",
          "confirm_password": "string"
        }
      },
      "ResetPasswordUpdateResponseModel": {
        "type": "object",
        "required": [
          "status",
          "data"
        ],
        "properties": {
          "status": {
            "type": "boolean"
          },
          "data": {
            "type": "object",
            "required": [
              "message"
            ],
            "properties": {
              "message": {
                "type": "string"
              }
            }
          }
        },
        "example": {
          "status": true,
          "data": {
            "message": "密碼已成功更新"
          }
        }
      },
      "UserInfoResponseModel": {
        "type": "object",
        "required": [
          "status",
          "data"
        ],
        "properties": {
          "status": {
            "type": "boolean"
          },
          "data": {
            "type": "object",
            "required": [
              "nick_name",
              "avator_image",
              "cart"
            ],
            "properties": {
              "nick_name": {
                "type": "string",
                "description": "使用者暱稱"
              },
              "avator_image": {
                "type": "string",
                "description": "使用者頭像"
              },
              "cart": {
                "type": "array",
                "description": "購物車項目集合",
                "items": {
                  "type": "object",
                  "description": "購物車項目",
                  "properties": {
                    "course_id": {
                      "type": "string",
                      "description": "課程ID"
                    },
                    "purchase_item_id": {
                      "type": "string",
                      "description": "購買項目ID"
                    }
                  }
                }
              }
            }
          }
        },
        "example": {
          "status": true,
          "data": {
            "nick_name": "string",
            "avator_image": "string",
            "cart": [
              {
                "course_id": "string",
                "purchase_item_id": "string"
              }
            ]
          }
        }
      },
      "GetCartItemsResponseModel": {
        "type": "object",
        "required": [
          "status",
          "data"
        ],
        "properties": {
          "status": {
            "type": "boolean"
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "course_id",
                "purchase_item_id",
                "image",
                "name",
                "quantity",
                "price",
                "main_category",
                "sub_category",
                "content"
              ],
              "properties": {
                "course_id": {
                  "type": "string"
                },
                "purchase_item_id": {
                  "type": "string"
                },
                "image": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "quantity": {
                  "type": "number"
                },
                "price": {
                  "type": "number"
                },
                "main_category": {
                  "type": "string"
                },
                "sub_category": {
                  "type": "string"
                },
                "content": {
                  "type": "string"
                }
              }
            }
          }
        },
        "example": {
          "status": true,
          "data": [
            {
              "course_id": "string",
              "purchase_item_id": "string",
              "image": "string",
              "name": "string",
              "quantity": 0,
              "price": 0,
              "main_category": "string",
              "sub_category": "string",
              "content": "string"
            }
          ]
        }
      },
      "AddCartItemRequestModel": {
        "type": "object",
        "required": [
          "course_id",
          "purchase_item_id"
        ],
        "properties": {
          "course_id": {
            "type": "string",
            "description": "課程Id"
          },
          "purchase_item_id": {
            "type": "string",
            "description": "課程項目Id"
          }
        },
        "example": {
          "course_id": "string",
          "purchase_item_id": "string"
        }
      },
      "AddCartItemResponseModel": {
        "type": "object",
        "required": [
          "status",
          "data"
        ],
        "properties": {
          "status": {
            "type": "boolean"
          },
          "data": {
            "type": "object",
            "required": [
              "message"
            ],
            "properties": {
              "message": {
                "type": "string"
              }
            }
          }
        },
        "example": {
          "status": true,
          "data": {
            "message": "加入購物車成功"
          }
        }
      },
      "RemoveCartItemResponseModel": {
        "type": "object",
        "required": [
          "status",
          "data"
        ],
        "properties": {
          "status": {
            "type": "boolean"
          },
          "data": {
            "type": "object",
            "required": [
              "message"
            ],
            "properties": {
              "message": {
                "type": "string"
              }
            }
          }
        },
        "example": {
          "status": true,
          "data": {
            "message": "刪除購物車成功"
          }
        }
      },
      "PostTeacherInfoRequestModel": {
        "type": "object",
        "required": [
          "user_id",
          "main_categorys",
          "sub_categorys",
          "application_status",
          "work_experiences",
          "learning_experience"
        ],
        "properties": {
          "user_id": {
            "type": "string",
            "description": "用戶的ID"
          },
          "avator_image": {
            "type": "string",
            "description": "用戶的頭像圖片URL"
          },
          "main_categorys": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "教授科目"
          },
          "sub_categorys": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "教授專長"
          },
          "application_status": {
            "type": "number",
            "description": "申請狀態"
          },
          "nationality": {
            "type": "string",
            "description": "國籍"
          },
          "introduction": {
            "type": "string",
            "description": "個人介紹"
          },
          "work_experiences": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "is_working": {
                  "type": "boolean",
                  "description": "是否在職中"
                },
                "workplace": {
                  "type": "string",
                  "description": "單位名稱"
                },
                "job_category": {
                  "type": "string",
                  "description": "職務類別"
                },
                "start_year": {
                  "type": "number",
                  "description": "開始年份"
                },
                "start_month": {
                  "type": "number",
                  "description": "開始月份"
                },
                "end_year": {
                  "type": "number",
                  "description": "結束年份"
                },
                "end_month": {
                  "type": "number",
                  "description": "結束月份"
                },
                "position": {
                  "type": "string",
                  "description": "職務名稱"
                },
                "place": {
                  "type": "string",
                  "description": "地點"
                }
              }
            },
            "description": "工作經歷"
          },
          "learning_experience": {
            "type": "object",
            "properties": {
              "is_in_school": {
                "type": "boolean",
                "description": "是否在學中"
              },
              "degree": {
                "type": "string",
                "description": "學歷"
              },
              "department": {
                "type": "string",
                "description": "科系名稱"
              },
              "start_year": {
                "type": "number",
                "description": "開始年份"
              },
              "start_month": {
                "type": "number",
                "description": "開始月份"
              },
              "end_year": {
                "type": "number",
                "description": "結束年份"
              },
              "end_month": {
                "type": "number",
                "description": "結束月份"
              },
              "name": {
                "type": "string",
                "description": "學校名稱"
              },
              "place": {
                "type": "string",
                "description": "地點"
              },
              "file": {
                "type": "string",
                "description": "文件路徑或參考"
              }
            },
            "description": "學習經歷"
          },
          "teaching_certificate": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "verifying_institution": {
                  "type": "string",
                  "description": "認證機構"
                },
                "license_name": {
                  "type": "string",
                  "description": "證書名稱"
                },
                "name": {
                  "type": "string",
                  "description": "持證人姓名"
                },
                "license_number": {
                  "type": "string",
                  "description": "證書編號"
                },
                "file": {
                  "type": "string",
                  "description": "文件路徑或參考"
                },
                "category": {
                  "type": "string",
                  "description": "類別"
                },
                "subject": {
                  "type": "string",
                  "description": "科目"
                }
              }
            },
            "description": "教學證書"
          },
          "intro_video_id": {
            "type": "string",
            "description": "自我介紹影片ID"
          },
          "courses": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "教授的課程"
          },
          "can_reserve_week": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "mon": {
                  "type": "array",
                  "items": {
                    "type": "number"
                  }
                },
                "tue": {
                  "type": "array",
                  "items": {
                    "type": "number"
                  }
                },
                "wed": {
                  "type": "array",
                  "items": {
                    "type": "number"
                  }
                },
                "thu": {
                  "type": "array",
                  "items": {
                    "type": "number"
                  }
                },
                "fri": {
                  "type": "array",
                  "items": {
                    "type": "number"
                  }
                },
                "sat": {
                  "type": "array",
                  "items": {
                    "type": "number"
                  }
                },
                "sun": {
                  "type": "array",
                  "items": {
                    "type": "number"
                  }
                }
              }
            },
            "description": "每週可預約的時段"
          }
        },
        "example": {
          "avator_image": "string",
          "main_categorys": [
            "string"
          ],
          "sub_categorys": [
            "string"
          ],
          "nationality": "string",
          "work_experiences": [
            {
              "is_working": false,
              "workplace": "string",
              "job_category": "string",
              "start_year": 2020,
              "start_month": 1,
              "end_year": 2021,
              "end_month": 12,
              "position": "string",
              "place": "string"
            }
          ],
          "learning_experience": {
            "is_in_school": false,
            "degree": "string",
            "department": "string",
            "start_year": 2016,
            "start_month": 9,
            "end_year": 2020,
            "end_month": 6,
            "name": "string",
            "place": "string",
            "file": "string"
          },
          "teaching_certificate": [
            {
              "verifying_institution": "string",
              "license_name": "string",
              "name": "string",
              "license_number": "string",
              "file": "string",
              "category": "string",
              "subject": "string"
            }
          ]
        }
      },
      "PostTeacherInfoResponseModel": {
        "type": "object",
        "required": [
          "status",
          "data"
        ],
        "properties": {
          "status": {
            "type": "boolean"
          },
          "data": {
            "type": "object",
            "required": [
              "message"
            ],
            "properties": {
              "message": {
                "type": "string"
              }
            }
          }
        },
        "example": {
          "status": true,
          "data": {
            "message": "申請成功"
          }
        }
      }
    }
  }
}